### ISSUE TITLE
[node-v6] Add support to Node v6 LTS

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/CartoDB-SQL-API#389]
Support for Node 0.10.x has ended in October 2016. We need to migrate to the latest Node LTS version (`v6.9.1`), for that we need:
 
 - [x] Check what dependencies don't work in Node v6 and need to be updated.
 - [x] Update forked repos and apply required changes.
 - [x] If necessary, implement changes to be Node v6 compatible.

cc @rochoa 

## TODO
 - [x] #393 Upgrade redis-mpool
 - [ ] #394 Upgrade node-cartodb-psql
 - [x] #395 Upgrade cartodb-redis
